export const ARTICLE_MAP: { [key: string]: { id: number, content: string}} = {
	history: {
    id: 1,
		content: "In the scorching summer of 101 BCE, on the broad plains near Vercellae (modern-day Vercelli in northern Italy), one of the Roman Republic\'s most decisive battles unfolded — the Battle of Vercellae. It marked the final clash between Rome and the migrating Cimbri, a Germanic tribe whose wanderings and invasions had terrorized the Roman north for years.\n\nThe Roman forces were commanded by Gaius Marius, a skilled general and reformer of the Roman military system, alongside his colleague Quintus Lutatius Catulus. Marius had already defeated the Teutones, the Cimbri\'s allies, at the Battle of Aquae Sextiae the year before. Now, with Rome\'s legions hardened and reorganized under his leadership, they prepared for the final confrontation.\n\nThe Cimbri, led by King Boiorix, reportedly offered battle in open terrain — a bold move, as it negated some of their earlier advantages in ambush and maneuver. Marius is said to have cleverly positioned his forces so that the early morning sun would shine into the eyes of the Cimbri, disrupting their vision and morale. The Roman infantry, well-trained and disciplined, held firm as the Cimbri charged. Despite their numbers, the tribal warriors broke under the pressure of Roman formations and cavalry flanks.\n\nBy the end of the day, tens of thousands of Cimbri lay dead or captured, including Boiorix himself. The Roman victory at Vercellae effectively ended the Cimbrian War, securing northern Italy and elevating Marius to legendary status among his soldiers and the Roman public.\n\nThe battle was not only a military triumph but also a political one. Marius granted Roman citizenship to Italian allies who had fought with him — a bold and controversial move that foreshadowed the broader struggles for citizenship and rights that would later rock the Republic. Vercellae thus became not just a battlefield, but a symbol of Rome\'s evolving identity and imperial destiny."
	},
  art: {
    id: 2,
		content: "In 1816, the English painter John Martin unveiled a breathtaking oil painting titled \"Joshua Commanding the Sun to Stand Still Upon Gibeon.\" This dramatic work captures the biblical moment described in the Book of Joshua, when the Israelite leader commands the sun and moon to halt in the sky, prolonging daylight so his forces could defeat the Amorites. Martin's interpretation is not a quiet biblical scene but a cinematic spectacle: the sky splits with divine light, armies clash on a vast battlefield, and celestial forces loom overhead.\n\nJohn Martin (1789-1854), largely self-taught, became renowned for his sweeping biblical and apocalyptic scenes, often set against sublime, tumultuous landscapes. Critics and admirers alike dubbed him a \"painter of the end of the world,\" owing to his fascination with judgment and cosmic power. His work reflected not only his religious interests but also the spirit of Romanticism, a movement that reveled in the sublime, the terrifying, and the majestic.\n\n“Joshua Commanding the Sun…” was Martin's first major success, shown at the British Institution in London, and it marked a turning point in his career. It combined the drama of biblical storytelling with the architectural grandeur and explosive light effects that would become his trademarks. Though controversial—some critics found his work too theatrical—Martin's bold vision captivated the public and even inspired writers like Thomas Carlyle and Edgar Allan Poe.\n\nToday, the painting is considered one of the earliest examples of biblical epic rendered in a near-cinematic scale, predating widescreen spectacle by more than a century. It stands as a testament to Martin's ambition: to paint not just scenes, but events so vast, even the heavens must pause."
  },
  paleontology: {
    id: 3,
		content: "In a quiet desert stretch of Montana, paleontologists recently unearthed a remarkably well-preserved Triceratops skeleton, its massive frill and three horns jutting from the sands like ancient monuments. Estimated to be over 66 million years old, the fossil gives rare insight into the late Cretaceous period and how these herbivores may have used their horns for defense and display. The discovery also included fossilized plant matter in the stomach area, suggesting a diet of cycads and ferns. Local researchers are calling it one of the most complete Triceratops finds in North America. Plans are already underway to reconstruct the skeleton for display at the Museum of the Rockies, bringing this prehistoric giant back to life for the public."
  },
  software: {
    id: 4,
		content: "Ruby on Rails was born not in a boardroom, but as a byproduct of a Danish programmer\'s side project. In the early 2000s, David Heinemeier Hansson (DHH) was working at 37signals (now Basecamp), a small web-based software company, when he began building the company\'s project management tool — Basecamp. To streamline development, DHH extracted reusable components into a framework using the Ruby programming language, admired for its elegance but not widely used in web development at the time. In 2004, he released this framework as Ruby on Rails, introducing key philosophies like convention over configuration and don't repeat yourself (DRY). Rails stood out by letting developers build full-featured web applications with far less code than was typical in Java or PHP. The framework caught fire, powering everything from GitHub to Shopify, and sparked a renaissance in web application design that still influences modern frameworks like Django, Laravel, and even aspects of JavaScript tooling today."
  },
  cars: {
    id: 5,
		content: "In April 1964, the world witnessed the debut of a car that would reshape American automotive culture: the Ford Mustang. Introduced at the New York World\'s Fair and simultaneously broadcast across U.S. television networks, the Mustang wasn't just a car — it was a revolution. With its long hood, short rear deck, and affordable price tag, it captured the spirit of freedom and performance that postwar America craved. Designed under the guidance of Lee Iacocca, the Mustang sold more than 22,000 units on its first day and over 400,000 in its first year, far exceeding expectations. Its success gave birth to an entirely new market segment — the “pony car” — and the Mustang became a cultural icon, immortalized in movies, music, and American muscle lore."
  },
  music: {
    id: 6,
		content: "On May 7, 1824, Ludwig van Beethoven took the stage at the Theater am Kärntnertor in Vienna to conduct the premiere of his Ninth Symphony — a work that would later become one of the most celebrated compositions in Western music. What made the night extraordinary wasn\'t just the music\'s scope, blending orchestra, soloists, and a full chorus, but the fact that Beethoven was almost completely deaf by then. Unaware of the audience\'s thunderous applause after the final movement, the contralto soloist had to gently turn him around so he could see the standing ovation he couldn\'t hear. It was a moment of human and artistic triumph: a composer defying isolation and illness to create one of the most uplifting works in history, including the iconic \"Ode to Joy.\" The performance marked Beethoven's last public appearance, but its legacy continues to echo across concert halls and global anthems to this day."
  }
};